version: '3.8'

services:
  deepclaude:
    image: ghcr.io/wsh307/deepclaude:latest
    container_name: deepclaude
    ports:
      - "8000:8000"  # API 端口
      - "8080:8080"  # Web 配置界面端口
    volumes:
      - ./config:/app/config  # 配置文件持久化
      - ./.env:/app/.env     # 环境变量文件
    environment:
      TZ: Asia/Shanghai
      PYTHONUNBUFFERED: "1"
      ENABLE_WEB_CONFIG: "true"
      WEB_CONFIG_PORT: "8080"
      WEB_CONFIG_PATH: "/admin"
      WEB_CONFIG_USERNAME: "${WEB_CONFIG_USERNAME:-admin}"
      WEB_CONFIG_PASSWORD: "${WEB_CONFIG_PASSWORD:-your_secure_password}"
      CONFIG_FILE_PATH: "/app/config/app_config.yaml"
    restart: always
    networks:
      - deepclaude_net

networks:
  deepclaude_net:
    driver: bridge